name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
   
      - name: print working message
        run: echo "The workflow is running and has access to your files!"
       
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list repo
        run: ls -la
     
        
