name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # هذه الخطوة أساسية لتجعل الـ Runner يرى ملفات الكود الخاص بك
      - name: Checkout code
        uses: actions/checkout@v4

      - name: print working message
        run: echo "The workflow is running and has access to your files!"
